### ISSUE TITLE
recipes-bsp/bootbin/xilinx-bootbin_1.0.bb fails to generate deps

### ISSUE THREAD

**Issue by dawithers** [Xilinx/meta-xilinx-tools#10]
Dropping the  `+ ":do_deploy"` from old line 76 in commit a622db9 seems to have broken this recipe. It now produces the following error:

> ERROR: Error for /home/ubuntu/git/yocto/poky/build/../../meta-xilinx-tools/recipes-bsp/bootbin/xilinx-bootbin_1.0.bb:do_configure[depends], dependency virtual/fsbl in '  virtual/fsbl virtual/fsbl virtual/fsbl virtual/fsbl virtual/fsbl virtual/bitstream virtual/pmu-firmware virtual/arm-trusted-firmware virtual/bootloader virtual/kernel virtual/dtb' does not contain exactly one ':' character.
>  Task 'depends' should be specified in the form 'packagename:task'
> ERROR: Command execution failed: Exited with 1

**Comment by mharth** [comment]
i think this is fixed in recent release, please confirm

**Comment by dawithers** [comment]
Not sure which release you were referring to, but I just tried it with 2019.2 and have the same issue. Adding back the do_deploy that I mentioned previously fixes the issue.
