### ISSUE TITLE
Upgrade to warrior

### ISSUE THREAD

**Issue by gpanders** [Xilinx/meta-xilinx-tools#16]
The `meta-xilinx` layers all support `warrior`; however, when trying to use `meta-xilinx-tools` I get the following error:

```
ERROR: Layer xilinx-tools is not compatible with the core layer which only supports these series: warrior (layer is compatible with thud)
```

**Comment by Ninic0c0** [comment]
And maybe zeus also?

**Comment by mhatle** [comment]
Just an FYI, we're not ignoring you.  We're in the process of updating a bunch of things (hopefully zeus will come soon as well.)

**Comment by r4space** [comment]
Any further news on this?

**Comment by Ninic0c0** [comment]
Quick and dirty workaround :

Edit conf/layer.conf file and add zeus as compatible 

**LAYERSERIES_COMPAT_xilinx-tools = "thud zeus"**

**Comment by ckalluri73** [comment]
Thank you for the comments. Our current master branch has been upgraded to work with Zeus. Please try it out and open new issues/pull requests. I will close this one.
