### ISSUE TITLE
XILINX_VER_MAIN  is set to 2019.2 on rel-v2020.1

### ISSUE THREAD

**Issue by dtrussel** [Xilinx/meta-xilinx-tools#23]
Is the `XILINX_VER_MAIN ??= "2019.2"` intentional in `conf/layer.conf` of the 2020.1 release?

**Comment by dtrussel** [comment]
This seems to be broken.
XSCT_TARBALL ?= "xsct_${XILINX_VER_MAIN}.tar.xz" then evaluates to `xsct_2019.2.tar.xz`. The downloaded tar archive however contains `Vitis/2020.1`, which is then not compatible with `XILINX_SDK_TOOLCHAIN ??= "${XSCT_STAGING_DIR}/Vitis/${XILINX_VER_MAIN}"`.
Which leads to `xsct` not being found.

**Comment by mhatle** [comment]
This was an oversight in the configuration.

In the PetaLinux release, the XILINX_VER_MAIN is set elsewhere.  We are working on Yocto Project configuration elements and will fix this in the near future.

Until then, I suggest just setting XILINX_VER_MAIN = "2020.1" in your local.conf file.

**Comment by dtrussel** [comment]
Thanks for the quick answer. I already set it in our layer, but was not sure if this is the intended way.
