### ISSUE TITLE
fpgautil source code linked from Wiki has moved

### ISSUE THREAD

**Issue by shareefj** [Xilinx/meta-xilinx-tools#46]
You have a Wiki entry referencing some out of date path to fpgautil.c.  Has this file been deprecated or just moved?  Any chance that the following Wiki entry can be updated:

https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18841847/Solution+ZynqMP+PL+Programming#SolutionZynqMPPLProgramming-ExercisingFPGAprogrammingusingfpgautil

**Comment by chkohn** [comment]
@shareefj please close this issue if it answers your question.

**Comment by shareefj** [comment]
Hi, thanks for that fast response and the updates look good.  Can you comment on where the best place to get support for debugging dt overlay issues is?  I'm trying to use `fpgautil` on a KV260 and am getting a `Failed to apply Overlay` error.

**Comment by grsandeep85** [comment]
Hi @shareefj ,

You can post in forum with complete logs. Either in Embedded Linux or KRIA board.

https://support.xilinx.com/s/topic/0TO2E000000YKXXWA4/embedded-linux?language=en_US
https://support.xilinx.com/s/topic/0TO2E000000YKXxWAO/kria-soms?language=en_US
