### ISSUE TITLE
SRC_URI concatenation is missing space

### ISSUE THREAD

**Issue by Gg9ngXK4qiDvvap** [Xilinx/meta-xilinx-tools#47]
The combination of SRC_URI appends, found here: https://github.com/Xilinx/meta-xilinx-tools/blob/master/recipes-bsp/device-tree/device-tree.bbappend#L44 is correct per line, but if a combination of lines are used, EXTRA_DT_FILES and EXTRA_OVERLAYS for example, the resulting SRC_URI has no space between the two appends.

A suggested fix:
SRC_URI:append = " ${@" ".join(["file://%s" % f for f in (d.getVar('EXTRA_DT_FILES') or "").split()])}"
SRC_URI:append = " ${@" ".join(["file://%s" % f for f in (d.getVar('EXTRA_OVERLAYS') or "").split()])}"

**Comment by grsandeep85** [comment]
Hi @Gg9ngXK4qiDvvap,

Thanks for reporting this issue I will take a look on this issue and get it fixed asap.

Thanks,
Sandeep
