### ISSUE TITLE
BOOT.bin is directly deployed to DEPLOY_DIR_IMAGE

### ISSUE THREAD

**Issue by kylemanna** [Xilinx/meta-xilinx-tools#5]
They `BOOT.bin` binary is directly written to the `${DEPLOY_DIR_IMAGE}` which bypasses all the shared state caching and deployment clean-ups.

The deploy class and `do_deploy` are the proper ways to implement this.  A warning is in the [Yocto Project Mega Manual](https://www.yoctoproject.org/docs/latest/mega-manual/mega-manual.html#ref-tasks-deploy):

> Caution
> Do not write the output directly to ${DEPLOY_DIR_IMAGE}, as this causes the sstate mechanism to malfunction.

This creates issues for me when BOOT.bin isn't deployed correctly breaking builds.  Additionally it isn't cleaned-up.

**Comment by mharth** [comment]
This is being changed and reworked as a recipe instead of a class, please see mailing list for the patch. You could change  DEPLOY_DIR_IMAGE to DEPLOYDIR to see of it fixes your issue

**Comment by kylemanna** [comment]
Thanks, can you share a link to a mailing list archive somewhere? Curious to learn more.

A receipe sounds like a better approach then a image class.

**Comment by mharth** [comment]
https://github.com/Xilinx/meta-xilinx-tools/blob/rel-v2018.1/recipes-bsp/bootbin/xilinx-bootbin_1.0.bb

Please join mailing list:
https://lists.yoctoproject.org/listinfo/meta-xilinx
