### ISSUE TITLE
fsbl-2018.2+gitAUTOINC+6e82c0183b-r0 do_Configure: Function Failed . 

### ISSUE THREAD

**Issue by haroonrl** [Xilinx/meta-xilinx-tools#9]
I don't why Petalinux -build fails while running the subjected function. I fetched latest 2018.2 version,.

DEBUG: Executing shell function do_configure
MISC_ARG is  -yamlconf /media/harry/7C64F70464F6C046/PetaLinux/test/build/tmp/work/plnx_zynqmp-xilinx-linux/fsbl/2018.2+gitAUTOINC+6e82c0183b-r0/fsbl.yaml
APP_ARG is  -app "Zynq MP FSBL"
cmd is: xsct /media/harry/7C64F70464F6C046/PetaLinux/test/build/tmp/work/plnx_zynqmp-xilinx-linux/fsbl/2018.2+gitAUTOINC+6e82c0183b-r0/app.tcl -ws /media/harry/7C64F70464F6C046/PetaLinux/test/build/../components/plnx_workspace/fsbl -pname fsbl -rp /media/harry/7C64F70464F6C046/PetaLinux/tools/hsm/data/embeddedsw -processor psu_cortexa53_0 -hdf /media/harry/7C64F70464F6C046/PetaLinux/test/build/tmp/deploy/images/plnx-zynqmp/Xilinx-plnx-zynqmp.hdf -arch 64  -app "Zynq MP FSBL"  -yamlconf /media/harry/7C64F70464F6C046/PetaLinux/test/build/tmp/work/plnx_zynqmp-xilinx-linux/fsbl/2018.2+gitAUTOINC+6e82c0183b-r0/fsbl.yaml
Display is :103
Source xsctrc script :/home/harry/.xsdbrc FAILED
Starting xsdk. This could take few seconds... Picked up _JAVA_OPTIONS: -Duser.home=/media/harry/7C64F70464F6C046/PetaLinux/test/build/tmp/xsctenv
done
No project(s) found in: '/media/harry/7C64F70464F6C046/PetaLinux/test/components/plnx_workspace/fsbl'
XSCTHELPER INFO: Empty WorkSpace
INFO: [Hsi 55-1698] elapsed time for repository loading 0 seconds
Channel closed
    while executing
"error [dict get $msg err]"
    (procedure "xsdk_eval" line 15)
    invoked from within
"xsdk_eval $chan "Xsdk" "setRepo" "o{Path s}" e [list [dict create Path [file normalize $repo_path]]]"
    (procedure "::sdk::set_user_repo_path_sdk" line 17)
    invoked from within
"::sdk::set_user_repo_path_sdk $params(set)"
    (procedure "repo" line 27)
    invoked from within
"repo -set $path"
    invoked from within
"if { $params(ws) ne "" } {
	#Local Work Space available
	setws $params(ws)
	if { [catch {importprojects $params(ws)} result] } {
		puts "XSCTHELPER IN..."
    (file "/media/harry/7C64F70464F6C046/PetaLinux/test/build/tmp/work/plnx_zynqmp-xilinx-linux/fsbl/2018.2+gitAUTOINC+6e82c0183b-r0/app.tcl" line 120)
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_configure (log file is located at /media/harry/7C64F70464F6C046/PetaLinux/test/build/tmp/work/plnx_zynqmp-xilinx-linux/fsbl/2018.2+gitAUTOINC+6e82c0183b-r0/temp/log.do_configure.9962)

**Comment by mharth** [comment]
can you do a cleansstate and retry ? something in xsct is failing to execute

**Comment by haroonrl** [comment]
Thanks for your suggestion but it didn't work. Same error.

**Comment by mharth** [comment]
xsct /media/harry/7C64F70464F6C046/PetaLinux/test/build/tmp/work/plnx_zynqmp-xilinx-linux/fsbl/2018.2+gitAUTOINC+6e82c0183b-r0/app.tcl -ws /media/harry/7C64F70464F6C046/PetaLinux/test/build/../components/plnx_workspace/fsbl -pname fsbl -rp /media/harry/7C64F70464F6C046/PetaLinux/tools/hsm/data/embeddedsw -processor psu_cortexa53_0 -hdf /media/harry/7C64F70464F6C046/PetaLinux/test/build/tmp/deploy/images/plnx-zynqmp/Xilinx-plnx-zynqmp.hdf -arch 64 -app "Zynq MP FSBL" -yamlconf /media/harry/7C64F70464F6C046/PetaLinux/test/build/tmp/work/plnx_zynqmp-xilinx-linux/fsbl/2018.2+gitAUTOINC+6e82c0183b-r0/fsbl.yaml


Can you run this command as-is without bitbake, just on the command line?

**Comment by haroonrl** [comment]
Not working even without bitbake

**Comment by mharth** [comment]
Some issue is xsct, can you reinstall yourX SDK. It should work manually, bitbake works on similar lines.
Can you also source XSDK and use xsct commands to see if they are working
